version: "0.2"
services:
  postgres_db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/11/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dev -U dev"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

  api:
    build: .
    command: bash -c "PYTHONPATH=. alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://dev:dev@postgres_db:5432/dev
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data: