services:
  api:
    build: ./src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://dev:dev@db:5432/dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dev -U dev"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: