"""init

Revision ID: 8eb70b796a14
Revises: 
Create Date: 2023-05-31 17:44:20.155536

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8eb70b796a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'short_urls',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('original_url', sa.String(length=255), nullable=True),
        sa.Column('short_url', sa.String(length=7), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_short_urls_short_url'),
        'short_urls',
        ['short_url'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_urls_short_url'), table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###
